//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTIC.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PTIC.Common.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဖြည့်စွက်ရန်လိုအပ်သည်။.
        /// </summary>
        public static string Message_NotNull {
            get {
                return ResourceManager.GetString("Message_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to မှတ်ချက် ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string Message_Remark_Require {
            get {
                return ResourceManager.GetString("Message_Remark_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အကြောင်းအရာ ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string Message_Subject_Require {
            get {
                return ResourceManager.GetString("Message_Subject_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine message box!.
        /// </summary>
        public static string UserMessage_MessageBox_Require {
            get {
                return ResourceManager.GetString("UserMessage_MessageBox_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to လက်ခံသူ ရွေးချယ်ပေးပါရန်။.
        /// </summary>
        public static string UserMessage_Receiver_Require {
            get {
                return ResourceManager.GetString("UserMessage_Receiver_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to လက်ခံသူ ရွေးချယ်ပေးပါရန်။.
        /// </summary>
        public static string UserMessage_ReceiverID_Require {
            get {
                return ResourceManager.GetString("UserMessage_ReceiverID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ပေးပို့သူ ရွေးချယ်ပေးပါရန်။.
        /// </summary>
        public static string UserMessage_Sender_Require {
            get {
                return ResourceManager.GetString("UserMessage_Sender_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine message action!.
        /// </summary>
        public static string UserMessage_SenderAction_Require {
            get {
                return ResourceManager.GetString("UserMessage_SenderAction_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ပေးပို့သူ ရွေးချယ်ပေးပါရန်။.
        /// </summary>
        public static string UserMessage_SenderID_Require {
            get {
                return ResourceManager.GetString("UserMessage_SenderID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine message status!.
        /// </summary>
        public static string UserMessage_Status_Require {
            get {
                return ResourceManager.GetString("UserMessage_Status_Require", resourceCulture);
            }
        }
    }
}
