//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTIC.Marketing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PTIC.Marketing.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &amp; P အမျိုးအစား ဖြည့်သွင်းပါရန်။.
        /// </summary>
        public static string A_P_UsageDetail_A_P_MaterialID_Select {
            get {
                return ResourceManager.GetString("A_P_UsageDetail_A_P_MaterialID_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &amp; P အရေအတွက် ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string A_P_UsageDetail_Qty_Select {
            get {
                return ResourceManager.GetString("A_P_UsageDetail_Qty_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment တွင် ကန့်သတ် အက္ခရာ အလုံးရေကျော်လွန်နေပါသည်။ 
        ///ကန့်သတ်အလုံးရေ = 500.
        /// </summary>
        public static string ComplaintComment_Comment_ExceedLength {
            get {
                return ResourceManager.GetString("ComplaintComment_Comment_ExceedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment ဖြည့်သွင်းပေးပါရန်။ 
        ///ကန့်သတ်အလုံးရေ = 500.
        /// </summary>
        public static string ComplaintComment_Comment_Require {
            get {
                return ResourceManager.GetString("ComplaintComment_Comment_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment အတွက် အမည်ရွေးချယ်ပေးပါရန်။.
        /// </summary>
        public static string ComplaintComment_CommentByEmployeeID_Require {
            get {
                return ResourceManager.GetString("ComplaintComment_CommentByEmployeeID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action တွင် ကန့်သတ် အက္ခရာ အလုံးရေကျော်လွန်နေပါသည်။ 
        ///ကန့်သတ်အလုံးရေ = 500.
        /// </summary>
        public static string ComplaintExplanation_Action_ExceedLength {
            get {
                return ResourceManager.GetString("ComplaintExplanation_Action_ExceedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action ဖြည့်သွင်းပေးပါရန်။
        /// ကန့်သတ်အလုံးရေ = 500.
        /// </summary>
        public static string ComplaintExplanation_Action_Require {
            get {
                return ResourceManager.GetString("ComplaintExplanation_Action_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation &amp; Action အတွက် အမည်ရွေးချယ်ပေးပါရန်။.
        /// </summary>
        public static string ComplaintExplanation_ExplainedByEmployeeID_Require {
            get {
                return ResourceManager.GetString("ComplaintExplanation_ExplainedByEmployeeID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation တွင် ကန့်သတ် အက္ခရာ အလုံးရေကျော်လွန်နေပါသည်။
        ///ကန့်သတ်အလုံးရေ = 500.
        /// </summary>
        public static string ComplaintExplanation_Explanation_ExceedLength {
            get {
                return ResourceManager.GetString("ComplaintExplanation_Explanation_ExceedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation ဖြည့်သွင်းပေးပါရန်။
        ///ကန့်သတ်အလုံးရေ = 500.
        /// </summary>
        public static string ComplaintExplanation_Explanation_Require {
            get {
                return ResourceManager.GetString("ComplaintExplanation_Explanation_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ထုတ်လုပ်သည့်နေ့ ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string ComplaintReceive_ProductionDate_Require {
            get {
                return ResourceManager.GetString("ComplaintReceive_ProductionDate_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received By ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string ComplaintReceive_ReceivedBy_Invalid {
            get {
                return ResourceManager.GetString("ComplaintReceive_ReceivedBy_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to လက်ခံ ရက်စွဲ မှန်ကန်စွာ ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string ComplaintReceive_ReceivedDate_Invalid {
            get {
                return ResourceManager.GetString("ComplaintReceive_ReceivedDate_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to သတင်းရရှိသည့်စနစ် ထည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string ComplaintReceive_ReceivedVia_Invalid {
            get {
                return ResourceManager.GetString("ComplaintReceive_ReceivedVia_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to သတင်းလက်ခံသူဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string ComplaintReceive_ReceiverID_Invalid {
            get {
                return ResourceManager.GetString("ComplaintReceive_ReceiverID_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to သတင်းပေးပို့သူဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string ComplaintReceive_Sender_Invalid {
            get {
                return ResourceManager.GetString("ComplaintReceive_Sender_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register ပြုလုပ်၍မရပါ။ Customer Complaint Received List မှတစ်ဆင့် ပြန်လည် Register ပြုလုပ်ပေးပါရန်။.
        /// </summary>
        public static string ComplaintRegister_ComplaintReceiveID_Invalid {
            get {
                return ResourceManager.GetString("ComplaintRegister_ComplaintReceiveID_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string ComplaintRegister_FromEmployeeID_Invalid {
            get {
                return ResourceManager.GetString("ComplaintRegister_FromEmployeeID_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string ComplaintRegister_ToEmployeeID_Invalid {
            get {
                return ResourceManager.GetString("ComplaintRegister_ToEmployeeID_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to နေ့ ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string InitialMarketingPlan_Day_Require {
            get {
                return ResourceManager.GetString("InitialMarketingPlan_Day_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to လမ်းကြောင်း ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string InitialMarketingPlan_RouteID_Require {
            get {
                return ResourceManager.GetString("InitialMarketingPlan_RouteID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupID ​ဖြည့်သွင်းပါရန်။.
        /// </summary>
        public static string InitialTeleMarketingPlan_GruopID_Require {
            get {
                return ResourceManager.GetString("InitialTeleMarketingPlan_GruopID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to နေ့စွဲ ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string InitialTeleMarketingPlan_PlanDate_Require {
            get {
                return ResourceManager.GetString("InitialTeleMarketingPlan_PlanDate_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string MobileServiecPlan_CustomerID_Require {
            get {
                return ResourceManager.GetString("MobileServiecPlan_CustomerID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string MobileServiecPlan_CusTypeID_Require {
            get {
                return ResourceManager.GetString("MobileServiecPlan_CusTypeID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to နေ့စွဲ ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string MobileServiecPlan_SvcPlanDate_Require {
            get {
                return ResourceManager.GetString("MobileServiecPlan_SvcPlanDate_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to မြို့နယ် ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string MobileServiecPlan_TownshipID_Require {
            get {
                return ResourceManager.GetString("MobileServiecPlan_TownshipID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဖြစ်ပေါ်လာသည့် အကြောင်းအရာ ရွေးချယ်ပေးပါရန်။.
        /// </summary>
        public static string ProductInComplaintReceive_ComplaintCaseID_Require {
            get {
                return ResourceManager.GetString("ProductInComplaintReceive_ComplaintCaseID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ထုတ်ကုန်အမည်ရွေးချယ်ပေးပါရန်။.
        /// </summary>
        public static string ProductInComplaintReceive_ProductID_Require {
            get {
                return ResourceManager.GetString("ProductInComplaintReceive_ProductID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အရေအတွက် ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string ProductInComplaintReceive_Qty_Require {
            get {
                return ResourceManager.GetString("ProductInComplaintReceive_Qty_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier အမည် ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string Supplier_SupplierName_Require {
            get {
                return ResourceManager.GetString("Supplier_SupplierName_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Type ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string Supplier_SupTypeID_Require {
            get {
                return ResourceManager.GetString("Supplier_SupTypeID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Type ဖြည့်သွင်းပါ။.
        /// </summary>
        public static string SupplierType_SupplierTypeName_Require {
            get {
                return ResourceManager.GetString("SupplierType_SupplierTypeName_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ခရီးစဉ် Plan စရက် ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string TripPlan_FromDate_Require {
            get {
                return ResourceManager.GetString("TripPlan_FromDate_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ခရီးစဉ် Plan ဆုံးရက် ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string TripPlan_ToDate_Require {
            get {
                return ResourceManager.GetString("TripPlan_ToDate_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Plan အမည် ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string TripPlan_TripPlanName_Require {
            get {
                return ResourceManager.GetString("TripPlan_TripPlanName_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အရောင်းကားသည် တူညီသည့် သွားမည့်ရက် နှင့် ပြန်ရောက်မည့်ရက် အတွင်း တစ်ကြိမ်ထက်ပိုသွား၍မရပါ။.
        /// </summary>
        public static string TripPlanDetail_duplicatedVan_Duplicate {
            get {
                return ResourceManager.GetString("TripPlanDetail_duplicatedVan_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to သွားမည့်ရက် ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string TripPlanDetail_FromDate_Require {
            get {
                return ResourceManager.GetString("TripPlanDetail_FromDate_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record ဖျက်၍မရပါ။.
        /// </summary>
        public static string TripPlanDetail_ID_Require {
            get {
                return ResourceManager.GetString("TripPlanDetail_ID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ခရီးစဉ်တာဝန်ခံသည် တူညီသည့် သွားမည့်ရက် နှင့် ပြန်ရောက်မည့်ရက် အတွင်း တစ်ကြိမ်ထက်ပိုသွား၍မရပါ။.
        /// </summary>
        public static string TripPlanDetail_ManagerID_Duplicate {
            get {
                return ResourceManager.GetString("TripPlanDetail_ManagerID_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ခရီးစဉ် တာဝန်ခံအမည် ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string TripPlanDetail_ManagerID_Require {
            get {
                return ResourceManager.GetString("TripPlanDetail_ManagerID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ပြန်ရောက်မည့်ရက် ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string TripPlanDetail_ToDate_Require {
            get {
                return ResourceManager.GetString("TripPlanDetail_ToDate_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ပို့ဆောင်ရေးစနစ် ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string TripPlanDetail_TransportTypeID_Require {
            get {
                return ResourceManager.GetString("TripPlanDetail_TransportTypeID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ခရီးစဉ်အမှတ် ထပ်၍ မရပါ။.
        /// </summary>
        public static string TripPlanDetail_TripPlanNo_Duplicate {
            get {
                return ResourceManager.GetString("TripPlanDetail_TripPlanNo_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အရောင်းကားနံပါတ် ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string TripPlanDetail_VenID_Require {
            get {
                return ResourceManager.GetString("TripPlanDetail_VenID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ပို့ဆောင်ရေးစနစ်သည် အရောင်းကားမဟုတ်သောကြောင့် အရောင်းကားနံပါတ်ရွေးချယ်ရန်မလိုပါ။.
        /// </summary>
        public static string TripPlanDetail_VenID_SetNull {
            get {
                return ResourceManager.GetString("TripPlanDetail_VenID_SetNull", resourceCulture);
            }
        }
    }
}
