//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTIC.Sale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PTIC.Sale.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to မြို့ ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string Address_TownID_Require {
            get {
                return ResourceManager.GetString("Address_TownID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to မြို့ သို့မဟုတ် မြို့နယ် ရွေးချယ်ပေးပါရန်။.
        /// </summary>
        public static string Address_TownIDOrTownshipID_Require {
            get {
                return ResourceManager.GetString("Address_TownIDOrTownshipID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to မြို့နယ် ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string Address_TownshipID_Require {
            get {
                return ResourceManager.GetString("Address_TownshipID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဘဏ်အမည် ထပ်၍ မရပါ။.
        /// </summary>
        public static string Bank_BankName_Duplicate {
            get {
                return ResourceManager.GetString("Bank_BankName_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဘဏ်အမည် ဖြည့်သွင်းပေးပါ။.
        /// </summary>
        public static string Bank_BankName_Require {
            get {
                return ResourceManager.GetString("Bank_BankName_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to မြို့အမည် ဖြည့်သွင်းပေးပါ။.
        /// </summary>
        public static string Bank_TownID_Require {
            get {
                return ResourceManager.GetString("Bank_TownID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ထုတ်ကုန် အမည်မထပ်ရပါ။.
        /// </summary>
        public static string Brand_BrandName_Duplicate {
            get {
                return ResourceManager.GetString("Brand_BrandName_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ပြိုင်ဖက်ထုတ်ကုန်အမျိုးအစား အမည်ဖြည့်သွင်းပေးပါ။.
        /// </summary>
        public static string Brand_BrandName_Require {
            get {
                return ResourceManager.GetString("Brand_BrandName_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ကုပ္မဏီအမည် ဖြည့်သွင်းပါ။.
        /// </summary>
        public static string Brand_CompanyName_Require {
            get {
                return ResourceManager.GetString("Brand_CompanyName_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ပြိုင်ဖက်ထုတ်ကုန် အမည်ဖြည့်သွင်းပေးပါ။.
        /// </summary>
        public static string Brand_CompetitorProductName_Require {
            get {
                return ResourceManager.GetString("Brand_CompetitorProductName_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer အမည် ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string Customer_CusName_Require {
            get {
                return ResourceManager.GetString("Customer_CusName_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer အမျိုးအစား ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string Customer_CusType_Require {
            get {
                return ResourceManager.GetString("Customer_CusType_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ခံစားခွင့်/လျှော့ဈေး သည် စုစုပေါင်း ကျသင့်ငွေထက် ပို၍မရပါ။.
        /// </summary>
        public static string Invoice_CommDiscAmt_GreaterThan_Total {
            get {
                return ResourceManager.GetString("Invoice_CommDiscAmt_GreaterThan_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer အမည် ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string Invoice_CusID_Require {
            get {
                return ResourceManager.GetString("Invoice_CusID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ပို့ရန်စာရင်းမှတဆင့် Invoice ထုတ်ရာတွင် ပို့ရန်စာရင်းအချက်အလက်လိုအပ်နေပါသည်။.
        /// </summary>
        public static string Invoice_DeliveryID_Require {
            get {
                return ResourceManager.GetString("Invoice_DeliveryID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ရက်စွဲ မှန်ကန်စွာ ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string Invoice_SalesDate_Invalid {
            get {
                return ResourceManager.GetString("Invoice_SalesDate_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အရောင်းဝန်ထမ်းအမည် ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string Invoice_SalesPersonID_Require {
            get {
                return ResourceManager.GetString("Invoice_SalesPersonID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အရောင်းစနစ် ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string Invoice_SaleType_Require {
            get {
                return ResourceManager.GetString("Invoice_SaleType_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to စုစုပေါင်းကျသင့်ငွေ လိုအပ်ပါသည်။.
        /// </summary>
        public static string Invoice_TotalAmt_Require {
            get {
                return ResourceManager.GetString("Invoice_TotalAmt_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ပို့ဆောင်သည့်ဂိတ်အမည် ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string Invoice_TransportGateID_Require {
            get {
                return ResourceManager.GetString("Invoice_TransportGateID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ပို့ဆောင်မှုစနစ် ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string Invoice_TransportTypeID_Require {
            get {
                return ResourceManager.GetString("Invoice_TransportTypeID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to လက်ငင်း (သို့) အကြွေး Voucher Type ရွေးချယ်ရန်လိုအပ်သည်။.
        /// </summary>
        public static string Invoice_VoucherType_Require {
            get {
                return ResourceManager.GetString("Invoice_VoucherType_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer အမည် ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string Order_CusID_Require {
            get {
                return ResourceManager.GetString("Order_CusID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order မှာသည့် နေ့စွဲ ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string Order_OrderDate_Invalid {
            get {
                return ResourceManager.GetString("Order_OrderDate_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order လက်ခံသူ ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string Order_OrderReceieverID_Require {
            get {
                return ResourceManager.GetString("Order_OrderReceieverID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ကျသင့်ငွေ မှားယွင်းနေသည်။.
        /// </summary>
        public static string OrderDetail_Amount_Invalid {
            get {
                return ResourceManager.GetString("OrderDetail_Amount_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ထုတ်ကုန် ထပ်၍ မရပါ။.
        /// </summary>
        public static string OrderDetail_ProductID_Duplicate {
            get {
                return ResourceManager.GetString("OrderDetail_ProductID_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order မှာမည့် ထုတ်ကုန် မှန်ကန်စွာရွေးချယ်ပေးပါ။.
        /// </summary>
        public static string OrderDetail_ProductID_Select {
            get {
                return ResourceManager.GetString("OrderDetail_ProductID_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order မှာမည့် အရေအတွက် သည် 0 အထက်ဖြစ်ရမည်။.
        /// </summary>
        public static string OrderDetail_Qty_GreaterThanZero {
            get {
                return ResourceManager.GetString("OrderDetail_Qty_GreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ရောင်းဈေးဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string OrderDetail_SalePrice_Require {
            get {
                return ResourceManager.GetString("OrderDetail_SalePrice_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type ရွေးချယ်ပေးပါရန်။.
        /// </summary>
        public static string Payment_CashReceiptType_Require {
            get {
                return ResourceManager.GetString("Payment_CashReceiptType_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Invoice No လိုအပ်ပါသည်။.
        /// </summary>
        public static string Payment_InvoiceID_Require {
            get {
                return ResourceManager.GetString("Payment_InvoiceID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment သည် Final မဟုတ်သောကြောင့် ယခုပေးငွေသည် ကျန်ငွေ ထက်ပို၍ (သို့မဟုတ်) တူညီ၍ မရပါ။.
        /// </summary>
        public static string Payment_PaidAmt_MustLessThanCreditAmt {
            get {
                return ResourceManager.GetString("Payment_PaidAmt_MustLessThanCreditAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ယခုပေးငွေသည် ကြွေးကျန်ငွေထက် ပို၍မရပါ။.
        /// </summary>
        public static string Payment_PaidAmt_MustLessThanOrEqualCreditAmt {
            get {
                return ResourceManager.GetString("Payment_PaidAmt_MustLessThanOrEqualCreditAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ယခုပေးငွေ ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string Payment_PaidAmt_Require {
            get {
                return ResourceManager.GetString("Payment_PaidAmt_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment ရွေးချယ်ပေးပါရန်။.
        /// </summary>
        public static string Payment_PayType_Require {
            get {
                return ResourceManager.GetString("Payment_PayType_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment တွင် First ( သို့မဟုတ် ) Final ရွေးချယ်ပေးပါရန်။.
        /// </summary>
        public static string Payment_PayType_Select_FirstOrFinal {
            get {
                return ResourceManager.GetString("Payment_PayType_Select_FirstOrFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment တွင် Partly ( သို့မဟုတ် ) Final ရွေးချယ်ပေးပါရန်။.
        /// </summary>
        public static string Payment_PayType_Select_PartialOrFinal {
            get {
                return ResourceManager.GetString("Payment_PayType_Select_PartialOrFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ကျသင့်ငွေ မှားယွင်းနေသည်။.
        /// </summary>
        public static string SaleDetail_Amount_Invalid {
            get {
                return ResourceManager.GetString("SaleDetail_Amount_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ထုတ်ကုန် မှန်ကန်စွာရွေးချယ်ပေးပါ။.
        /// </summary>
        public static string SaleDetail_ProductID_Invalid {
            get {
                return ResourceManager.GetString("SaleDetail_ProductID_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အရေအတွက် ဖြည့်သွင်းပေးပါ။.
        /// </summary>
        public static string SaleDetail_Qty_Require {
            get {
                return ResourceManager.GetString("SaleDetail_Qty_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ရောင်းဈေး မှန်ကန်စွာဖြည့်သွင်းပေးပါ။.
        /// </summary>
        public static string SaleDetail_SalePrice_Require {
            get {
                return ResourceManager.GetString("SaleDetail_SalePrice_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ထံအကြောင်းကြားရက် ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string SalesService_ContactDateToCustomer_Require {
            get {
                return ResourceManager.GetString("SalesService_ContactDateToCustomer_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to စက်ရုံမှ ပြန်ရသည့်နေ့ ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string SalesService_DateFromFactory_Require {
            get {
                return ResourceManager.GetString("SalesService_DateFromFactory_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVC မှပြန်‌ပေးသည့်‌နေ့ ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string SalesService_DateFromSvc_Require {
            get {
                return ResourceManager.GetString("SalesService_DateFromSvc_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer သို့ပြန်‌ပေးသည့်‌နေ့ ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string SalesService_DateToCustomer_Require {
            get {
                return ResourceManager.GetString("SalesService_DateToCustomer_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to စက်ရုံသို့ပေးသည့်နေ့ ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string SalesService_DateToFactory_Require {
            get {
                return ResourceManager.GetString("SalesService_DateToFactory_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVC သို့ပေးသည့်နေ့ ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string SalesService_DateToSvc_Require {
            get {
                return ResourceManager.GetString("SalesService_DateToSvc_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ပေးသူ ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string SalesService_Giver_Require {
            get {
                return ResourceManager.GetString("SalesService_Giver_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job No ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string SalesService_JobNo_Require {
            get {
                return ResourceManager.GetString("SalesService_JobNo_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ထုတ်ကုန် မှန်ကန်စွာရွေးချယ်ပေးပါ။.
        /// </summary>
        public static string SalesService_ProductID_Select {
            get {
                return ResourceManager.GetString("SalesService_ProductID_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ရက်စွဲ မှန်ကန်စွာ ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string SalesService_ReceivedDate_Invalid {
            get {
                return ResourceManager.GetString("SalesService_ReceivedDate_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer အားဆောင်ရွက်ပေးမှု ရွေးချယ်ပေးပါရန်။.
        /// </summary>
        public static string SalesService_Service_Require {
            get {
                return ResourceManager.GetString("SalesService_Service_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service ဆောင်ရွက်သည့်နေ့ ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string SalesService_SeviceDate_Require {
            get {
                return ResourceManager.GetString("SalesService_SeviceDate_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to လက်ခံသူ ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string SalesService_Taker_Require {
            get {
                return ResourceManager.GetString("SalesService_Taker_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlet User Info တွင် User အမည် ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string ServicedCustomer_CustomerID_Require {
            get {
                return ResourceManager.GetString("ServicedCustomer_CustomerID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End User Info တွင် မြို့ ရွေးချယ်ပေးပါရန်။.
        /// </summary>
        public static string ServicedCustomer_TownID_Require {
            get {
                return ResourceManager.GetString("ServicedCustomer_TownID_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End User Info တွင် User အမည် ဖြည့်သွင်းပေးပါရန်။.
        /// </summary>
        public static string ServicedCustomer_UserName_Require {
            get {
                return ResourceManager.GetString("ServicedCustomer_UserName_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to မြို့အမည် ထပ်၍ မရပါ။.
        /// </summary>
        public static string TownInTrip_TownID_Duplicate {
            get {
                return ResourceManager.GetString("TownInTrip_TownID_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to မြို့ ရွေးချယ်ပေးပါရန်။.
        /// </summary>
        public static string TownInTrip_TownID_Invalid {
            get {
                return ResourceManager.GetString("TownInTrip_TownID_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ခရီးစဉ် ရွေးချယ်ပေးပါရန်။.
        /// </summary>
        public static string TownInTrip_TripID_Invalid {
            get {
                return ResourceManager.GetString("TownInTrip_TripID_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဂိတ်အမည် ထပ်၍ မရပါ။.
        /// </summary>
        public static string TransportGate_GateName_Duplicate {
            get {
                return ResourceManager.GetString("TransportGate_GateName_Duplicate", resourceCulture);
            }
        }
    }
}
