//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTIC {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PTIC.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ထည့်မည်.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဘဏ်.
        /// </summary>
        internal static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အိုးသစ္ႏွင့္ အိုးခြံသတ္မွတ္ခ်က္.
        /// </summary>
        internal static string BatterySetting {
            get {
                return ResourceManager.GetString("BatterySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အမှတ်တံဆိပ်.
        /// </summary>
        internal static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_green_right_arrow {
            get {
                object obj = ResourceManager.GetObject("btn_green_right_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_green_vertical {
            get {
                object obj = ResourceManager.GetObject("btn_green_vertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ထည့်မည်.
        /// </summary>
        internal static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Discount.
        /// </summary>
        internal static string btnCashDiscount {
            get {
                return ResourceManager.GetString("btnCashDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ထုတ်ကုန်အမျိုးအစား.
        /// </summary>
        internal static string btnCategory {
            get {
                return ResourceManager.GetString("btnCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ပိတ်မည်.
        /// </summary>
        internal static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Class.
        /// </summary>
        internal static string btnCustomerClass {
            get {
                return ResourceManager.GetString("btnCustomerClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Transfer.
        /// </summary>
        internal static string btnDataTransfer {
            get {
                return ResourceManager.GetString("btnDataTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဖျက်မည်.
        /// </summary>
        internal static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        internal static string btnDelivery {
            get {
                return ResourceManager.GetString("btnDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ပြင်မည်.
        /// </summary>
        internal static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.O ပစ္စည်းအဝင်အထွက်.
        /// </summary>
        internal static string btnHO {
            get {
                return ResourceManager.GetString("btnHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile POS.
        /// </summary>
        internal static string btnMobilePOS {
            get {
                return ResourceManager.GetString("btnMobilePOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to စာဝင် / စာထွက်.
        /// </summary>
        internal static string btnMsgInOut {
            get {
                return ResourceManager.GetString("btnMsgInOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string btnOrder {
            get {
                return ResourceManager.GetString("btnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ပါကင်‌လျှော့‌ဈေး.
        /// </summary>
        internal static string btnPkgCommission {
            get {
                return ResourceManager.GetString("btnPkgCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Change.
        /// </summary>
        internal static string btnPriceChange {
            get {
                return ResourceManager.GetString("btnPriceChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ထုတ်ကုန်.
        /// </summary>
        internal static string btnProduct {
            get {
                return ResourceManager.GetString("btnProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string btnReport {
            get {
                return ResourceManager.GetString("btnReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to လမ်းကြောင်း.
        /// </summary>
        internal static string btnRoute {
            get {
                return ResourceManager.GetString("btnRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Device.
        /// </summary>
        internal static string btnSaleAssignDev {
            get {
                return ResourceManager.GetString("btnSaleAssignDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string btnSaleCustomer {
            get {
                return ResourceManager.GetString("btnSaleCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string btnSales {
            get {
                return ResourceManager.GetString("btnSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Commission.
        /// </summary>
        internal static string btnSalesCommission {
            get {
                return ResourceManager.GetString("btnSalesCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Type.
        /// </summary>
        internal static string btnSalesType {
            get {
                return ResourceManager.GetString("btnSalesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string btnSaleUser {
            get {
                return ResourceManager.GetString("btnSaleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to သိမ်းမည်.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string btnService {
            get {
                return ResourceManager.GetString("btnService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string btnSetup {
            get {
                return ResourceManager.GetString("btnSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ထုတ်ကုန်အမျိုးအစားခွဲ.
        /// </summary>
        internal static string btnSubCategory {
            get {
                return ResourceManager.GetString("btnSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to မြို့.
        /// </summary>
        internal static string btnTown {
            get {
                return ResourceManager.GetString("btnTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to မြို့နယ်.
        /// </summary>
        internal static string btnTownship {
            get {
                return ResourceManager.GetString("btnTownship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ပို့‌ဆောင်‌ရေးဂိတ်.
        /// </summary>
        internal static string btnTransportGate {
            get {
                return ResourceManager.GetString("btnTransportGate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ခရီးစဉ်.
        /// </summary>
        internal static string btnTrip {
            get {
                return ResourceManager.GetString("btnTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ခရီးစဉ်.
        /// </summary>
        internal static string btnTripSetup {
            get {
                return ResourceManager.GetString("btnTripSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company ထုတ်ပစ္စည်း.
        /// </summary>
        internal static string chkIsOwnerBrand {
            get {
                return ResourceManager.GetString("chkIsOwnerBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Notification.
        /// </summary>
        internal static string chkShowNotification {
            get {
                return ResourceManager.GetString("chkShowNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဆက်သွယ်ရမည့်သူအမည်.
        /// </summary>
        internal static string ContactPersonName {
            get {
                return ResourceManager.GetString("ContactPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer အမည္.
        /// </summary>
        internal static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVC အိုးအပြီးပေးရန်.
        /// </summary>
        internal static string CVC_Battery {
            get {
                return ResourceManager.GetString("CVC_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ရောင်းဈေးမရှိသေးပါ။ သတ်မှတ်ရန်လိုအပ်ပါမည်။.
        /// </summary>
        internal static string DefinePrice {
            get {
                return ResourceManager.GetString("DefinePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        internal static string deleteConfirmation {
            get {
                return ResourceManager.GetString("deleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        internal static string Delivered {
            get {
                return ResourceManager.GetString("Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ထုတ်ကုန်ထပ်နေသည်။.
        /// </summary>
        internal static string DuplicateProduct {
            get {
                return ResourceManager.GetString("DuplicateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End User.
        /// </summary>
        internal static string EndUser {
            get {
                return ResourceManager.GetString("EndUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ** Please enter password. **.
        /// </summary>
        internal static string EnterPwd {
            get {
                return ResourceManager.GetString("EnterPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to နေ့စွဲရွေးချယ်ပေးပါ။.
        /// </summary>
        internal static string err_fill_date {
            get {
                return ResourceManager.GetString("err_fill_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဌာနအမည် ရွေးချယ်ပေးပါ။.
        /// </summary>
        internal static string err_fill_department {
            get {
                return ResourceManager.GetString("err_fill_department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to တာဝန်ခံ ရွေးချယ်ပေးပါ။.
        /// </summary>
        internal static string err_fill_incharge {
            get {
                return ResourceManager.GetString("err_fill_incharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to စာအမှတ် ဖြည့်သွင်းရန်လိုအပ်သည်။.
        /// </summary>
        internal static string err_fill_return_no {
            get {
                return ResourceManager.GetString("err_fill_return_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အပ်နှံပြီး POSM စာရင်းများကို ပြန်လည်ပြင်ဆင်၍မရပါ။
        ///Row အသစ်ထည့်သွင်းခြင်း နှင့် ဖျက်ခြင်းများကိုသာလျှင် System မှ လုပ်ဆောင်သွားမည်ဖြစ်သည်။.
        /// </summary>
        internal static string err_prohibit_save_returned_ap {
            get {
                return ResourceManager.GetString("err_prohibit_save_returned_ap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အသုံးပြုထားသည်။ ဖျက်ခွင့်မရှိပါ။.
        /// </summary>
        internal static string errCantDelete {
            get {
                return ResourceManager.GetString("errCantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer မရှိ‌သေးပါ.
        /// </summary>
        internal static string errCustomer {
            get {
                return ResourceManager.GetString("errCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current DateTime is Wrong ! Check your computer clock..
        /// </summary>
        internal static string errDateTime {
            get {
                return ResourceManager.GetString("errDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your network setting or database.
        /// </summary>
        internal static string errDBorNet {
            get {
                return ResourceManager.GetString("errDBorNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to စီစဉ်ပြီးသော စာရင်းများကို ဖျက်ခွင့်မရှိပါ။.
        /// </summary>
        internal static string errDel {
            get {
                return ResourceManager.GetString("errDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ခရီးစဉ်မှားယွင်းနေပါသည်။.
        /// </summary>
        internal static string errduplicateTrip {
            get {
                return ResourceManager.GetString("errduplicateTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ခရီးစဉ်ရက်တူပါက ခရီးစဉ်အမည် ၊ မော်တော်ယာဉ် ၊ တာဝန်ခံအမည်များထပ်၍ မရပါ။.
        /// </summary>
        internal static string errduplicateVanTripStaff {
            get {
                return ResourceManager.GetString("errduplicateVanTripStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save data!.
        /// </summary>
        internal static string errFailedToSave {
            get {
                return ResourceManager.GetString("errFailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဓာတ်ပုံအရေအတွက် ကျော်လွန်နေပါသည်။.
        /// </summary>
        internal static string errImageCountOver {
            get {
                return ResourceManager.GetString("errImageCountOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity must be filled!.
        /// </summary>
        internal static string errMustFillQty {
            get {
                return ResourceManager.GetString("errMustFillQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to လမ်း‌ကြောင်းအရင်သိမ်း‌ပေးပါ။.
        /// </summary>
        internal static string errNeedToSaveRoute {
            get {
                return ResourceManager.GetString("errNeedToSaveRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ခရီးစဉ်ကို အရင်သိမ်း‌ပေးပါ။.
        /// </summary>
        internal static string errNeedToSaveTrip {
            get {
                return ResourceManager.GetString("errNeedToSaveTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date ‌ရွေးပါ။.
        /// </summary>
        internal static string errPlanDate {
            get {
                return ResourceManager.GetString("errPlanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Quantity!.
        /// </summary>
        internal static string errQty {
            get {
                return ResourceManager.GetString("errQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity must be integer!.
        /// </summary>
        internal static string errQtyMustBeInt {
            get {
                return ResourceManager.GetString("errQtyMustBeInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ထည့်သွင်း‌ပေးရန်လိုအပ်‌သော အချက်အလက်များ.
        /// </summary>
        internal static string errRequiredFields {
            get {
                return ResourceManager.GetString("errRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ပြင်လို‌သော စာ‌ကြောင်းကို‌ရွေးပါ။.
        /// </summary>
        internal static string errSelectModifyRecord {
            get {
                return ResourceManager.GetString("errSelectModifyRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Row!.
        /// </summary>
        internal static string errSelectRow {
            get {
                return ResourceManager.GetString("errSelectRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ပယ်ဖျက်လို‌သော Row ကို‌ရွေးချယ်‌ပေးပါ။.
        /// </summary>
        internal static string errSelectRowToDelete {
            get {
                return ResourceManager.GetString("errSelectRowToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a row to be edited!.
        /// </summary>
        internal static string errSelectRowToEdit {
            get {
                return ResourceManager.GetString("errSelectRowToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to တိုင်းဒေသကြီး (သို့) ပြည်နယ် ဖြည့်ရန် လိုအပ်သည်။.
        /// </summary>
        internal static string errStateDivisionMustFill {
            get {
                return ResourceManager.GetString("errStateDivisionMustFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been deleted successfully..
        /// </summary>
        internal static string errSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("errSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to မြို့အမည်  ဖြည့်ရန် လိုအပ်သည်။.
        /// </summary>
        internal static string errTownEmpty {
            get {
                return ResourceManager.GetString("errTownEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to မြို့အမည် ဖြည့်ရန် လိုအပ်သည်။.
        /// </summary>
        internal static string errTownMustFill {
            get {
                return ResourceManager.GetString("errTownMustFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to မြို့နယ်အမည် ဖြည့်ရန် လိုအပ်သည်။.
        /// </summary>
        internal static string errTownshipMustFill {
            get {
                return ResourceManager.GetString("errTownshipMustFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load data!.
        /// </summary>
        internal static string FailedToLoadData {
            get {
                return ResourceManager.GetString("FailedToLoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter following field(s):\n.
        /// </summary>
        internal static string FillFields {
            get {
                return ResourceManager.GetString("FillFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Brand.
        /// </summary>
        internal static string frmBrand {
            get {
                return ResourceManager.GetString("frmBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government.
        /// </summary>
        internal static string Government {
            get {
                return ResourceManager.GetString("Government", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ** Incorrect password! **.
        /// </summary>
        internal static string IncorrectPwd {
            get {
                return ResourceManager.GetString("IncorrectPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အမှတ်တံဆိပ်.
        /// </summary>
        internal static string lblBrandName {
            get {
                return ResourceManager.GetString("lblBrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand အတည်ပြုသည့်‌နေ့.
        /// </summary>
        internal static string lblConfirmBrand {
            get {
                return ResourceManager.GetString("lblConfirmBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to မှတ်ချက်.
        /// </summary>
        internal static string lblRemark {
            get {
                return ResourceManager.GetString("lblRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand စတင်သုံးစွဲသည့်‌နေ့.
        /// </summary>
        internal static string lblStartBrand {
            get {
                return ResourceManager.GetString("lblStartBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker {
            get {
                object obj = ResourceManager.GetObject("marker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ပြင်မည်.
        /// </summary>
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &amp; P Material.
        /// </summary>
        internal static string msg_hd_ap {
            get {
                return ResourceManager.GetString("msg_hd_ap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require field values.
        /// </summary>
        internal static string msg_hd_require_field_values {
            get {
                return ResourceManager.GetString("msg_hd_require_field_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to မပို့နိုင်သော Order စာရင်း သို့ ပေးပို့လိုပါသလား?.
        /// </summary>
        internal static string msg_qst_lost_order {
            get {
                return ResourceManager.GetString("msg_qst_lost_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load invoices vouchers!.
        /// </summary>
        internal static string msg_text_err_failed_to_load_invoices {
            get {
                return ResourceManager.GetString("msg_text_err_failed_to_load_invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load data.
        /// </summary>
        internal static string msg_title_err_failed_to_load_data {
            get {
                return ResourceManager.GetString("msg_title_err_failed_to_load_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some fields are missing! Please fill it..
        /// </summary>
        internal static string msg_txt_err_missing_field_value {
            get {
                return ResourceManager.GetString("msg_txt_err_missing_field_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer အမည် ဖြည့်သွင်းပေးပါ။.
        /// </summary>
        internal static string msg_txt_fill_customer_name {
            get {
                return ResourceManager.GetString("msg_txt_fill_customer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order မှာယူမှုစာရင်း မှန်ကန်စွာ ဖြည့်သွင်းပေးပါ။.
        /// </summary>
        internal static string msg_txt_fill_order_details {
            get {
                return ResourceManager.GetString("msg_txt_fill_order_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order လက်ခံသူ ဖြည့်သွင်းပေးပါ။.
        /// </summary>
        internal static string msg_txt_fill_order_receiver_name {
            get {
                return ResourceManager.GetString("msg_txt_fill_order_receiver_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ပို့ရမည့်အ‌ရေအတွက် ဖြည့်သွင်းပေးပါ။.
        /// </summary>
        internal static string msg_txt_require_delivery_qty {
            get {
                return ResourceManager.GetString("msg_txt_require_delivery_qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to return service battery to customer?.
        /// </summary>
        internal static string msgCaptionReturnToCustomer {
            get {
                return ResourceManager.GetString("msgCaptionReturnToCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Saved..
        /// </summary>
        internal static string msgSuccessfullySaved {
            get {
                return ResourceManager.GetString("msgSuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to Save? Please check Departments and Employees are corrected..
        /// </summary>
        internal static string msgSureSave {
            get {
                return ResourceManager.GetString("msgSureSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string msgSureToReturn {
            get {
                return ResourceManager.GetString("msgSureToReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ကိန်းဂဏန်းသာဖြည့်ပါ။.
        /// </summary>
        internal static string MustIntegerQty {
            get {
                return ResourceManager.GetString("MustIntegerQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အိုးသစ်ပေးရန်.
        /// </summary>
        internal static string NewBattery {
            get {
                return ResourceManager.GetString("NewBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notification_right {
            get {
                object obj = ResourceManager.GetObject("notification_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notification_wrong {
            get {
                object obj = ResourceManager.GetObject("notification_wrong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not planned.
        /// </summary>
        internal static string NotPlanned {
            get {
                return ResourceManager.GetString("NotPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အခြား.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned.
        /// </summary>
        internal static string Planned {
            get {
                return ResourceManager.GetString("Planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ထုတ်ကုန်အမျိုးအစား.
        /// </summary>
        internal static string ProductCategory {
            get {
                return ResourceManager.GetString("ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ထုတ်ကုန်.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this marketing detail?.
        /// </summary>
        internal static string qstSureToDeleteMarketingDetail {
            get {
                return ResourceManager.GetString("qstSureToDeleteMarketingDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this mobile service detail?.
        /// </summary>
        internal static string qstSureToDeleteMobileServiceDetail {
            get {
                return ResourceManager.GetString("qstSureToDeleteMobileServiceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete a selected row?.
        /// </summary>
        internal static string qstSureToDeleteRow {
            get {
                return ResourceManager.GetString("qstSureToDeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အိုးခွံအ‌ရေအတွက်.
        /// </summary>
        internal static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ပြုပြင်ပေးရန်.
        /// </summary>
        internal static string Repair {
            get {
                return ResourceManager.GetString("Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ဖြည့်စွက်ရန်လိုအပ်သည်။.
        /// </summary>
        internal static string RequiredQty {
            get {
                return ResourceManager.GetString("RequiredQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to သတိပေးချက်.
        /// </summary>
        internal static string Restrist {
            get {
                return ResourceManager.GetString("Restrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Outlet.
        /// </summary>
        internal static string RetailOutlet {
            get {
                return ResourceManager.GetString("RetailOutlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ထုတ်ကုန်အမျိုးအစားခွဲ.
        /// </summary>
        internal static string SubCategory {
            get {
                return ResourceManager.GetString("SubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to သတ်မှတ်သည့်‌နေ့.
        /// </summary>
        internal static string TranDate {
            get {
                return ResourceManager.GetString("TranDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undelivered.
        /// </summary>
        internal static string Undelivered {
            get {
                return ResourceManager.GetString("Undelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ကြည့်မည်.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to လက်ကျန်.
        /// </summary>
        internal static string warn_hd_insufficient_qty {
            get {
                return ResourceManager.GetString("warn_hd_insufficient_qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ရွေးချယ်ထားသော A &amp; P Material သည်  {0} ဌာန တွင် မရှိပါ။.
        /// </summary>
        internal static string warn_txt_ap_doesnot_exist_in_dept {
            get {
                return ResourceManager.GetString("warn_txt_ap_doesnot_exist_in_dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to လက်ကျန် &apos;{0}&apos; သာကျန်ရှိသဖြင့် မလုံလောက်ပါ။.
        /// </summary>
        internal static string warn_txt_insufficient_ap_qty {
            get {
                return ResourceManager.GetString("warn_txt_insufficient_ap_qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to သတိပေးချက်.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to အိုးခွံအ‌လေးချိန်.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wholesale Outlet.
        /// </summary>
        internal static string WholesaleOutlet {
            get {
                return ResourceManager.GetString("WholesaleOutlet", resourceCulture);
            }
        }
    }
}
